obj-$(CONFIG_ARCH_SOPHGO)		+= intc/pcie_intc.o
obj-$(CONFIG_ARCH_SOPHGO)		+= rxu/rxu.o
obj-$(CONFIG_ARCH_SOPHGO)		+= pcie_ep/
obj-$(CONFIG_ARCH_SOPHGO)		+= ap_sgcard/
obj-$(CONFIG_ARCH_SOPHGO)		+= tp_driver/
obj-$(CONFIG_ARCH_SOPHGO)		+= pcie_phy/
obj-$(CONFIG_ARCH_SOPHGO)		+= pcie_device/
obj-$(CONFIG_ARCH_SOPHGO)		+= c2c_rc/
