obj-$(CONFIG_SOC_SOPHGO)		+= intc/pcie_intc.o
obj-$(CONFIG_SOC_SOPHGO)		+= rxu/rxu.o
obj-$(CONFIG_SOC_SOPHGO)		+= pcie_ep/
obj-$(CONFIG_SOC_SOPHGO)		+= ap_sgcard/
obj-$(CONFIG_SOC_SOPHGO)		+= tp_driver/