# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SOPHGO) += sg2260-ap-full.dtb
dtb-$(CONFIG_ARCH_SOPHGO) += sg2260-ap-lite.dtb
dtb-$(CONFIG_ARCH_SOPHGO) += sg2260-rp-full.dtb
dtb-$(CONFIG_ARCH_SOPHGO) += sg2260-rp-lite.dtb
dtb-$(CONFIG_ARCH_SOPHGO) += sg2260-tp-pld.dtb
